# First implementation of Machine Learning Algorithm

In this file, we are going to import data from a file .csv that we take from chornograf.
We have to parse him and put into an array.
Finally we will insert some machin Learning algorithm with the librairy sklearn.

To do this, we will use some librairy as pandas, matplotlib, numpy, sklearn and some others.


Le fichier data2learn2.csv a pour query ceci : 

SELECT mean("moisture-percent") AS "mean_moisture-percent" ,  mean("temperature") AS "mean_temperature"

FROM "demeter"."autogen"."chirp-left" 

WHERE time > now() - 1200h AND time < now() -700h

GROUP BY time(30m)

In [2]:
import csv
import math
import matplotlib.pyplot as plt
import numpy as np

#Data place 
tabl = []

name = 'Data2learn.csv'
nameTabl = []
with open(name) as csv_file:
    csv_reader = csv.reader(csv_file, delimiter=',')
    ligne = 0
    for row in csv_reader:
        if ligne != 0:
            i = 0
            for el in row:
                tabl[i].append(el)
                i += 1
        else:
            for el in row:
                tabl.append([])
                nameTabl.append(el)
                
        ligne += 1
        
#print(tabl)
print(nameTabl)



['date', 'mean_moisture-percent', 'mean_temperature']


# Import des données 

Leccture d'un fichier csv en un fichier dataframe.

Création d'une base dataframe avec comme colonne le temps, l'humidité, la tempérture, l'humidité + 1, la température + 1.

Il faut régler le problème tu dernier temps.

In [20]:
import csv
import math
import pandas as pd
import numpy as np

df = pd.read_csv('Data2learn2.csv')
#print(df)
#print(df.iloc[:,2])

#Création des deux autres colonnes
df['moistureAdd'] = df.index
df['temperatureAdd'] = df.index

# size
nligne = df.shape[0]
nColumn = df.shape[1]
tmp = np.linspace(0,nligne-2,nligne-1,dtype=int)
df.iloc[tmp, 3] = pd.Series(np.append(df.iloc[tmp+1,1].to_numpy()-df.iloc[tmp,1].to_numpy(),0), index=df.index)
df.iloc[tmp, 4] = pd.Series(np.append(df.iloc[tmp+1,2].to_numpy()-df.iloc[tmp,2].to_numpy(),0), index=df.index)

#Ajout de la ligne
df.iloc[nligne-1, 3] = 0
df.iloc[nligne-1, 4] = 0


#df


date  mean_moisture-percent  \
0      3/8/2019 11:30:00.000000000 PM              31.436364   
1      3/9/2019 12:00:00.000000000 AM              31.360000   
2      3/9/2019 12:30:00.000000000 AM              31.363333   
3       3/9/2019 1:00:00.000000000 AM              31.353333   
4       3/9/2019 1:30:00.000000000 AM              31.303333   
5       3/9/2019 2:00:00.000000000 AM              31.360000   
6       3/9/2019 2:30:00.000000000 AM              31.416667   
7       3/9/2019 3:00:00.000000000 AM              31.406667   
8       3/9/2019 3:30:00.000000000 AM              31.363333   
9       3/9/2019 4:00:00.000000000 AM              31.366667   
10      3/9/2019 4:30:00.000000000 AM              31.323333   
11      3/9/2019 5:00:00.000000000 AM              31.296667   
12      3/9/2019 5:30:00.000000000 AM              31.276667   
13      3/9/2019 6:00:00.000000000 AM              31.343333   
14      3/9/2019 6:30:00.000000000 AM              31.333333   
15      3/9/2019 7:00:00.000000000 AM              31.410000   
16      3/9/2019 7:30:00.000000000 AM              31.366667   
17      3/9/2019 8:00:00.000000000 AM              31.430000   
18      3/9/2019 8:30:00.000000000 AM              31.383333   
19      3/9/2019 9:00:00.000000000 AM              31.356667   
20      3/9/2019 9:30:00.000000000 AM              31.366667   
21     3/9/2019 10:00:00.000000000 AM              31.410000   
22     3/9/2019 10:30:00.000000000 AM              31.540000   
23     3/9/2019 11:00:00.000000000 AM              37.271667   
24     3/9/2019 11:30:00.000000000 AM              35.583333   
25     3/9/2019 12:00:00.000000000 PM              35.160000   
26     3/9/2019 12:30:00.000000000 PM              34.813333   
27      3/9/2019 1:00:00.000000000 PM              34.440000   
28      3/9/2019 1:30:00.000000000 PM              34.340000   
29      3/9/2019 2:00:00.000000000 PM              33.943333   
...                               ...                    ...   
971    3/29/2019 5:00:00.000000000 AM              13.910000   
972    3/29/2019 5:30:00.000000000 AM              13.816667   
973    3/29/2019 6:00:00.000000000 AM              13.806667   
974    3/29/2019 6:30:00.000000000 AM              13.833333   
975    3/29/2019 7:00:00.000000000 AM              13.750000   
976    3/29/2019 7:30:00.000000000 AM              13.813333   
977    3/29/2019 8:00:00.000000000 AM              13.840000   
978    3/29/2019 8:30:00.000000000 AM              13.846667   
979    3/29/2019 9:00:00.000000000 AM              14.283333   
980    3/29/2019 9:30:00.000000000 AM              14.016667   
981   3/29/2019 10:00:00.000000000 AM              13.720000   
982   3/29/2019 10:30:00.000000000 AM              13.590000   
983   3/29/2019 11:00:00.000000000 AM              21.226667   
984   3/29/2019 11:30:00.000000000 AM              17.355000   
985   3/29/2019 12:00:00.000000000 PM              16.646667   
986   3/29/2019 12:30:00.000000000 PM              15.893333   
987    3/29/2019 1:00:00.000000000 PM              15.263333   
988    3/29/2019 1:30:00.000000000 PM              14.686667   
989    3/29/2019 2:00:00.000000000 PM              14.133333   
990    3/29/2019 2:30:00.000000000 PM              13.733333   
991    3/29/2019 3:00:00.000000000 PM              13.166667   
992    3/29/2019 3:30:00.000000000 PM              12.820000   
993    3/29/2019 4:00:00.000000000 PM              12.780000   
994    3/29/2019 4:30:00.000000000 PM              13.553333   
995    3/29/2019 5:00:00.000000000 PM              13.886667   
996    3/29/2019 5:30:00.000000000 PM              13.973333   
997    3/29/2019 6:00:00.000000000 PM              13.953333   
998    3/29/2019 6:30:00.000000000 PM              13.870000   
999    3/29/2019 7:00:00.000000000 PM              13.776667   
1000   3/29/2019 7:30:00.000000000 PM              13.900000   

      mean_temperature  moistureAdd  temperatureAdd  
0         

# Ajout de l'arrosage

L'arrosage est ajouté au temps 10h30.

In [21]:
df['Arosage'] = df.index
liste10h30 = np.linspace(22,982,int((982-22)/48)+1)


df.iloc[:,5] = 0
for i in liste10h30:
    df.iloc[int(i),5] = 10
df


date  mean_moisture-percent  \
0      3/8/2019 11:30:00.000000000 PM              31.436364   
1      3/9/2019 12:00:00.000000000 AM              31.360000   
2      3/9/2019 12:30:00.000000000 AM              31.363333   
3       3/9/2019 1:00:00.000000000 AM              31.353333   
4       3/9/2019 1:30:00.000000000 AM              31.303333   
5       3/9/2019 2:00:00.000000000 AM              31.360000   
6       3/9/2019 2:30:00.000000000 AM              31.416667   
7       3/9/2019 3:00:00.000000000 AM              31.406667   
8       3/9/2019 3:30:00.000000000 AM              31.363333   
9       3/9/2019 4:00:00.000000000 AM              31.366667   
10      3/9/2019 4:30:00.000000000 AM              31.323333   
11      3/9/2019 5:00:00.000000000 AM              31.296667   
12      3/9/2019 5:30:00.000000000 AM              31.276667   
13      3/9/2019 6:00:00.000000000 AM              31.343333   
14      3/9/2019 6:30:00.000000000 AM              31.333333   
15      3/9/2019 7:00:00.000000000 AM              31.410000   
16      3/9/2019 7:30:00.000000000 AM              31.366667   
17      3/9/2019 8:00:00.000000000 AM              31.430000   
18      3/9/2019 8:30:00.000000000 AM              31.383333   
19      3/9/2019 9:00:00.000000000 AM              31.356667   
20      3/9/2019 9:30:00.000000000 AM              31.366667   
21     3/9/2019 10:00:00.000000000 AM              31.410000   
22     3/9/2019 10:30:00.000000000 AM              31.540000   
23     3/9/2019 11:00:00.000000000 AM              37.271667   
24     3/9/2019 11:30:00.000000000 AM              35.583333   
25     3/9/2019 12:00:00.000000000 PM              35.160000   
26     3/9/2019 12:30:00.000000000 PM              34.813333   
27      3/9/2019 1:00:00.000000000 PM              34.440000   
28      3/9/2019 1:30:00.000000000 PM              34.340000   
29      3/9/2019 2:00:00.000000000 PM              33.943333   
...                               ...                    ...   
971    3/29/2019 5:00:00.000000000 AM              13.910000   
972    3/29/2019 5:30:00.000000000 AM              13.816667   
973    3/29/2019 6:00:00.000000000 AM              13.806667   
974    3/29/2019 6:30:00.000000000 AM              13.833333   
975    3/29/2019 7:00:00.000000000 AM              13.750000   
976    3/29/2019 7:30:00.000000000 AM              13.813333   
977    3/29/2019 8:00:00.000000000 AM              13.840000   
978    3/29/2019 8:30:00.000000000 AM              13.846667   
979    3/29/2019 9:00:00.000000000 AM              14.283333   
980    3/29/2019 9:30:00.000000000 AM              14.016667   
981   3/29/2019 10:00:00.000000000 AM              13.720000   
982   3/29/2019 10:30:00.000000000 AM              13.590000   
983   3/29/2019 11:00:00.000000000 AM              21.226667   
984   3/29/2019 11:30:00.000000000 AM              17.355000   
985   3/29/2019 12:00:00.000000000 PM              16.646667   
986   3/29/2019 12:30:00.000000000 PM              15.893333   
987    3/29/2019 1:00:00.000000000 PM              15.263333   
988    3/29/2019 1:30:00.000000000 PM              14.686667   
989    3/29/2019 2:00:00.000000000 PM              14.133333   
990    3/29/2019 2:30:00.000000000 PM              13.733333   
991    3/29/2019 3:00:00.000000000 PM              13.166667   
992    3/29/2019 3:30:00.000000000 PM              12.820000   
993    3/29/2019 4:00:00.000000000 PM              12.780000   
994    3/29/2019 4:30:00.000000000 PM              13.553333   
995    3/29/2019 5:00:00.000000000 PM              13.886667   
996    3/29/2019 5:30:00.000000000 PM              13.973333   
997    3/29/2019 6:00:00.000000000 PM              13.953333   
998    3/29/2019 6:30:00.000000000 PM              13.870000   
999    3/29/2019 7:00:00.000000000 PM              13.776667   
1000   3/29/2019 7:30:00.000000000 PM              13.900000   

      mean_temperature  moistureAdd  temperatureAdd  Arosage  
0

# Analyse de la dataFrame


# Linear Regression Multiple Variables



In [22]:
from sklearn import linear_model

reg = linear_model.LinearRegression()
reg.fit(df[['mean_moisture-percent','mean_temperature','Arosage']],df.moistureAdd)



LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [23]:
reg.coef_

array([-0.01839499, -0.01968661,  0.75019812])

In [24]:
reg.intercept_

0.77237249129829655

In [34]:
reg.predict([[31,25,10]])[0]

7.211943710937156

# Test de mes résultats

Le but est de faire une boucle sur une période en utilisant les valeurs obtenus à l'itérations précédentes

Creation de liste de planification de l'arrosage pour le test

In [44]:
TestSize = 20 #Taille du Test

testArrosage = np.zeros(TestSize)
testArrosage[2] = 10  #Position de notre arrosage et valeur
testArrosage

array([  0.,   0.,  10.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.])

Création de la liste de plannification de la temperature pour notre test

In [43]:
PosTemperature = np.linspace(980,980+TestSize-1,TestSize)
testTemperature = (df.iloc[PosTemperature, 2]).values
testTemperature

array([ 23.80166667,  25.42333333,  26.02666667,  25.07666667,
        26.195     ,  27.54833333,  30.95      ,  34.26      ,
        34.71      ,  36.22      ,  37.        ,  39.77166667,
        41.91333333,  40.08666667,  30.915     ,  28.08      ,
        27.91333333,  27.76166667,  27.52166667,  27.095     ])

Mise en place du test sur le nombre d'itération souhaité

In [41]:
StartHumidity = 10
result = np.zeros(TestSize)
for i in range(0,TestSize):
    result[i] = StartHumidity + reg.predict([[StartHumidity,testTemperature[i],testArrosage[i]]])[0]
    StartHumidity = result[i]

result

array([ 10.11984839,  10.20556705,  25.28179367,  25.09543323,
        24.89048469,  24.66266362,  24.37206603,  24.02165127,
        23.66882342,  23.29275904,  22.90825681,  22.47626275,
        22.01005306,  21.58838016,  21.355023  ,  21.18176999,
        21.01498507,  20.85425396,  20.70120429,  20.55936958])