# First implementation of Machine Learning Algorithm

In this file, we are going to import data from a file .csv that we take from chornograf.
We have to parse him and put into an array.
Finally we will insert some machin Learning algorithm with the librairy sklearn.

To do this, we will use some librairy as pandas, matplotlib, numpy, sklearn and some others.


Le fichier data2learn2.csv a pour query ceci : 

SELECT mean("moisture-percent") AS "mean_moisture-percent" ,  mean("temperature") AS "mean_temperature"

FROM "demeter"."autogen"."chirp-left" 

WHERE time > now() - 1200h AND time < now() -700h

GROUP BY time(30m)

In [26]:
from sklearn import linear_model
import csv
import math
import matplotlib.pyplot as plt
import numpy as np

In [1]:
#Data place 
tabl = []

name = 'Data2learn.csv'
nameTabl = []
with open(name) as csv_file:
    csv_reader = csv.reader(csv_file, delimiter=',')
    ligne = 0
    for row in csv_reader:
        if ligne != 0:
            i = 0
            for el in row:
                tabl[i].append(el)
                i += 1
        else:
            for el in row:
                tabl.append([])
                nameTabl.append(el)
                
        ligne += 1
        
#print(tabl)
print(nameTabl)



['date', 'mean_moisture-percent', 'mean_temperature']


# Import des données 

Leccture d'un fichier csv en un fichier dataframe.

Création d'une base dataframe avec comme colonne le temps, l'humidité, la tempérture, l'humidité + 1, la température + 1.

Il faut régler le problème tu dernier temps.

In [2]:
df = pd.read_csv('Data2learn2.csv')
#print(df)
#print(df.iloc[:,2])

#Création des deux autres colonnes
df['moistureAdd'] = df.index
df['temperatureAdd'] = df.index

# size
nligne = df.shape[0]
nColumn = df.shape[1]
tmp = np.linspace(0,nligne-2,nligne-1,dtype=int)
df.iloc[tmp, 3] = pd.Series(np.append(df.iloc[tmp+1,1].to_numpy()-df.iloc[tmp,1].to_numpy(),0), index=df.index)
df.iloc[tmp, 4] = pd.Series(np.append(df.iloc[tmp+1,2].to_numpy()-df.iloc[tmp,2].to_numpy(),0), index=df.index)

#Ajout de la ligne
df.iloc[nligne-1, 3] = 0
df.iloc[nligne-1, 4] = 0


#df


## Ajout de l'arrosage

L'arrosage est ajouté au temps 10h30.

In [3]:
df['Arrosage'] = df.index
liste10h30 = np.linspace(22,982,int((982-22)/48)+1)

df.iloc[:,5] = 0
for i in liste10h30:
    if i >= 934:
        df.iloc[int(i),5] = 20
    else:
        df.iloc[int(i),5] = 10



Ajout du temps après chaque arrosage

In [4]:
df['TAfterArrosage'] = df.index

df.iloc[:,6] = 0
for i in np.append(-26,liste10h30):
    for j in range(0,48):
        if i+j < nligne:
            df.iloc[int(i+j),6] = j*30

df


date  mean_moisture-percent  \
0      3/8/2019 11:30:00.000000000 PM              31.436364   
1      3/9/2019 12:00:00.000000000 AM              31.360000   
2      3/9/2019 12:30:00.000000000 AM              31.363333   
3       3/9/2019 1:00:00.000000000 AM              31.353333   
4       3/9/2019 1:30:00.000000000 AM              31.303333   
5       3/9/2019 2:00:00.000000000 AM              31.360000   
6       3/9/2019 2:30:00.000000000 AM              31.416667   
7       3/9/2019 3:00:00.000000000 AM              31.406667   
8       3/9/2019 3:30:00.000000000 AM              31.363333   
9       3/9/2019 4:00:00.000000000 AM              31.366667   
10      3/9/2019 4:30:00.000000000 AM              31.323333   
11      3/9/2019 5:00:00.000000000 AM              31.296667   
12      3/9/2019 5:30:00.000000000 AM              31.276667   
13      3/9/2019 6:00:00.000000000 AM              31.343333   
14      3/9/2019 6:30:00.000000000 AM              31.333333   
15      3/9/2019 7:00:00.000000000 AM              31.410000   
16      3/9/2019 7:30:00.000000000 AM              31.366667   
17      3/9/2019 8:00:00.000000000 AM              31.430000   
18      3/9/2019 8:30:00.000000000 AM              31.383333   
19      3/9/2019 9:00:00.000000000 AM              31.356667   
20      3/9/2019 9:30:00.000000000 AM              31.366667   
21     3/9/2019 10:00:00.000000000 AM              31.410000   
22     3/9/2019 10:30:00.000000000 AM              31.540000   
23     3/9/2019 11:00:00.000000000 AM              37.271667   
24     3/9/2019 11:30:00.000000000 AM              35.583333   
25     3/9/2019 12:00:00.000000000 PM              35.160000   
26     3/9/2019 12:30:00.000000000 PM              34.813333   
27      3/9/2019 1:00:00.000000000 PM              34.440000   
28      3/9/2019 1:30:00.000000000 PM              34.340000   
29      3/9/2019 2:00:00.000000000 PM              33.943333   
...                               ...                    ...   
971    3/29/2019 5:00:00.000000000 AM              13.910000   
972    3/29/2019 5:30:00.000000000 AM              13.816667   
973    3/29/2019 6:00:00.000000000 AM              13.806667   
974    3/29/2019 6:30:00.000000000 AM              13.833333   
975    3/29/2019 7:00:00.000000000 AM              13.750000   
976    3/29/2019 7:30:00.000000000 AM              13.813333   
977    3/29/2019 8:00:00.000000000 AM              13.840000   
978    3/29/2019 8:30:00.000000000 AM              13.846667   
979    3/29/2019 9:00:00.000000000 AM              14.283333   
980    3/29/2019 9:30:00.000000000 AM              14.016667   
981   3/29/2019 10:00:00.000000000 AM              13.720000   
982   3/29/2019 10:30:00.000000000 AM              13.590000   
983   3/29/2019 11:00:00.000000000 AM              21.226667   
984   3/29/2019 11:30:00.000000000 AM              17.355000   
985   3/29/2019 12:00:00.000000000 PM              16.646667   
986   3/29/2019 12:30:00.000000000 PM              15.893333   
987    3/29/2019 1:00:00.000000000 PM              15.263333   
988    3/29/2019 1:30:00.000000000 PM              14.686667   
989    3/29/2019 2:00:00.000000000 PM              14.133333   
990    3/29/2019 2:30:00.000000000 PM              13.733333   
991    3/29/2019 3:00:00.000000000 PM              13.166667   
992    3/29/2019 3:30:00.000000000 PM              12.820000   
993    3/29/2019 4:00:00.000000000 PM              12.780000   
994    3/29/2019 4:30:00.000000000 PM              13.553333   
995    3/29/2019 5:00:00.000000000 PM              13.886667   
996    3/29/2019 5:30:00.000000000 PM              13.973333   
997    3/29/2019 6:00:00.000000000 PM              13.953333   
998    3/29/2019 6:30:00.000000000 PM              13.870000   
999    3/29/2019 7:00:00.000000000 PM              13.776667   
1000   3/29/2019 7:30:00.000000000 PM              13.900000   

      mean_temperature  moistureAdd  temperatureAdd  Arrosage  T

# Analyse de la dataFrame


## Linear Regression Multiple Variables sans l'information sur le temps sans arrosage



In [5]:
reg = linear_model.LinearRegression()
reg.fit(df[['mean_moisture-percent','mean_temperature','Arrosage']],df.moistureAdd)


LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [6]:
reg.coef_

array([-0.01619655, -0.02062898,  0.64269237])

In [7]:
reg.intercept_

0.75662954892605394

In [8]:
reg.predict([[31,25,10]])[0]

6.1657357937024271

## Linear Regression Multiple Variables AVEC l'information sur le temps sans arrosage

In [52]:
reg2 = linear_model.LinearRegression()
reg2.fit(df[['mean_moisture-percent','mean_temperature','Arrosage','TAfterArrosage']],df.moistureAdd)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [53]:
reg2.coef_

array([ -5.70216010e-03,   1.31717487e-02,   6.78979076e-01,
         4.91427599e-04])

In [54]:
reg2.intercept_

-0.73980634783026533

In [55]:
reg2.predict([[31,25,10,0]])[0]

6.2025111667703925

# Test de mes résultats

SANS DES DONNÉES POUR VERIFICATIONS. PAS DE DATA TEST.

Le but est de faire une boucle sur une période en utilisant les valeurs obtenus à l'itérations précédentes

Creation de liste de planification de l'arrosage pour le test

In [13]:
TestSize = 20 #Taille du Test

testArrosage = np.zeros(TestSize)
testArrosage[2] = 10  #Position de notre arrosage et valeur
testArrosage

array([  0.,   0.,  10.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.])

Création de la liste de plannification de la temperature pour notre test

In [14]:
PosTemperature = np.linspace(980,980+TestSize-1,TestSize)
testTemperature = (df.iloc[PosTemperature, 2]).values
testTemperature

array([ 23.80166667,  25.42333333,  26.02666667,  25.07666667,
        26.195     ,  27.54833333,  30.95      ,  34.26      ,
        34.71      ,  36.22      ,  37.        ,  39.77166667,
        41.91333333,  40.08666667,  30.915     ,  28.08      ,
        27.91333333,  27.76166667,  27.52166667,  27.095     ])

Mise en place du test sur le nombre d'itération souhaité

In [15]:
StartHumidity = 10
result = np.zeros(TestSize)
for i in range(0,TestSize):
    result[i] = StartHumidity + reg.predict([[StartHumidity,testTemperature[i],testArrosage[i]]])[0]
    StartHumidity = result[i]

result

array([ 10.10365999,  10.17218771,  16.65408308,  16.62366794,
        16.57067535,  16.49062317,  16.34169465,  16.12689634,
        15.90629397,  15.65811485,  15.39786476,  15.08465318,
        14.73233414,  14.42340373,  14.30867904,  14.25429565,
        14.20423125,  14.15810645,  14.11767966,  14.08670935])



## Test avec data Test

Création d'une data frame pour effectuer les tests.

Voici la query effectuer pour obtenir les données.

SELECT mean("moisture-percent") AS "mean_moisture-percent" ,  mean("temperature") AS "mean_temperature"

FROM "demeter"."autogen"."chirp-left" 

WHERE time > now() - 700h AND time < now() -400h

GROUP BY time(30m)

In [56]:
dfTest = pd.read_csv('DataTest.csv')

dfTest['moistureAdd'] = dfTest.index
dfTest['temperatureAdd'] = dfTest.index


# size
nligneTest = dfTest.shape[0]
nColumnTest = dfTest.shape[1]
tmp = np.linspace(0,nligneTest-2,nligneTest-1,dtype=int)
dfTest.iloc[tmp, 3] = pd.Series(np.append(dfTest.iloc[tmp+1,1].to_numpy()-dfTest.iloc[tmp,1].to_numpy(),0), index=dfTest.index)
dfTest.iloc[tmp, 4] = pd.Series(np.append(dfTest.iloc[tmp+1,2].to_numpy()-dfTest.iloc[tmp,2].to_numpy(),0), index=dfTest.index)

#Ajout de la ligne
dfTest.iloc[nligneTest-1, 3] = 0


In [57]:
dfTest['Arrosage'] = dfTest.index
liste11h30 = np.linspace(31,559,int((559-31)/48)+1)

dfTest.iloc[:,5] = 0
for i in liste11h30:
    dfTest.iloc[int(i),5] = 20



In [59]:
dfTest['TAfterArrosage'] = dfTest.index

dfTest.iloc[:,6] = 0
for i in np.append(-17,liste11h30):
    for j in range(0,48):
        if i+j < nligneTest:
            dfTest.iloc[int(i+j),6] = j*30

dfTest.iloc[range(28,46),:]

date  mean_moisture-percent  mean_temperature  \
28  3/31/2019 10:00:00.000000000 AM              13.380000         26.165000   
29  3/31/2019 10:30:00.000000000 AM              13.376667         26.005000   
30  3/31/2019 11:00:00.000000000 AM              13.263333         26.213333   
31  3/31/2019 11:30:00.000000000 AM              13.273333         26.350000   
32  3/31/2019 12:00:00.000000000 PM              21.736667         24.565000   
33  3/31/2019 12:30:00.000000000 PM              17.828333         25.441667   
34   3/31/2019 1:00:00.000000000 PM              17.096667         27.123333   
35   3/31/2019 1:30:00.000000000 PM              16.403333         30.118333   
36   3/31/2019 2:00:00.000000000 PM              16.240000         32.915000   
37   3/31/2019 2:30:00.000000000 PM              15.986667         33.665000   
38   3/31/2019 3:00:00.000000000 PM              15.293333         35.393333   
39   3/31/2019 3:30:00.000000000 PM              14.696667         35.616667   
40   3/31/2019 4:00:00.000000000 PM              13.770000         40.160000   
41   3/31/2019 4:30:00.000000000 PM              13.153333         42.818333   
42   3/31/2019 5:00:00.000000000 PM              13.310000         39.663333   
43   3/31/2019 5:30:00.000000000 PM              14.006667         31.276667   
44   3/31/2019 6:00:00.000000000 PM              14.366667         29.038333   
45   3/31/2019 6:30:00.000000000 PM              14.430000         28.526667   

    moistureAdd  temperatureAdd  Arrosage  TAfterArrosage  
28    -0.003333       -0.160000         0            1350  
29    -0.113333        0.208333         0            1380  
30     0.010000        0.136667         0            1410  
31     8.463333       -1.785000        20               0  
32    -3.908333        0.876667         0              30  
33    -0.731667        1.681667         0              60  
34    -0.693333        2.995000         0              90  
35    -0.163333        2.796667         0             120  
36    -0.253333        0.750000         0             150  
37    -0.693333        1.728333         0             180  
38    -0.596667        0.223333         0             210  
39    -0.926667        4.543333         0             240  
40    -0.616667        2.658333         0             270  
41     0.156667       -3.155000         0             300  
42     0.696667       -8.386667         0             330  
43     0.360000       -2.238333         0             360  
44     0.063333       -0.511667         0             390  
45    -0.066667       -0.378333         0             420

## Test avec les donnes SANS le temps

In [83]:
init = 32+48*1
StartHumidity = dfTest.iloc[init,1]

TestSize = 40
result = np.zeros(TestSize)
for i in range(0,TestSize):
    result[i] = StartHumidity + reg.predict([[StartHumidity,dfTest.iloc[init+i,2],dfTest.iloc[init+i,5]]])[0]
    StartHumidity = result[i]

#print(result)

#print(dfTest.iloc[range(0+init+1,TestSize+init+1),1])
ErrSansTemps = np.mean(dfTest.iloc[range(0+init+1,TestSize+init+1),1].values-result)
print("Moyenne d'erreur : ",ErrSansTemps)

Moyenne d'erreur :  -4.64522098199


## Test avec les donnes AVEC le temps

In [85]:
init = 32+48*1
StartHumidity = dfTest.iloc[init,1]

TestSize = 40
result2 = np.zeros(TestSize)
for i in range(0,TestSize):
    result2[i] = StartHumidity + reg2.predict([[StartHumidity,dfTest.iloc[init+i,2],dfTest.iloc[init+i,5],dfTest.iloc[init+i,6]]])[0]
    StartHumidity = result2[i]

#print(result2)
#print(dfTest.iloc[range(0+init+1,TestSize+init+1),1])
ErrTemps = np.mean(dfTest.iloc[range(0+init+1,TestSize+init+1),1].values-result2)
print("Moyenne d'erreur : ",ErrTemps)

Moyenne d'erreur :  -2.21106280251


# Partage de la Data frame

Partage de la data frame en deux. 

Une partie qui contient que les moments où on arrose. On peut selectionner ceci grace à loc et à df['TAfterArrosage'] == 0. Quand on arrose, le temps après arrosage est de 0.

L'autre partie contient les moments où on n'arrose pas. C'est-à-dire les momments où l'eau s'évapore.

In [74]:
dfArrosage = df.loc[df['TAfterArrosage'] == 0]
dfEvaporation = df.loc[df['TAfterArrosage'] > 0]

dfArrosage

date  mean_moisture-percent  mean_temperature  \
22    3/9/2019 10:30:00.000000000 AM              31.540000         25.706667   
70   3/10/2019 10:30:00.000000000 AM              31.476667         24.918333   
118  3/11/2019 10:30:00.000000000 AM              30.920000         24.921667   
166  3/12/2019 10:30:00.000000000 AM              28.846667         25.735000   
214  3/13/2019 10:30:00.000000000 AM              26.445000         21.938333   
262  3/14/2019 10:30:00.000000000 AM              23.970000         24.131667   
310  3/15/2019 10:30:00.000000000 AM              24.576667         25.705000   
358  3/16/2019 10:30:00.000000000 AM              24.570000         25.576667   
406  3/17/2019 10:30:00.000000000 AM              22.900000         26.516667   
454  3/18/2019 10:30:00.000000000 AM              22.120000         23.031667   
502  3/19/2019 10:30:00.000000000 AM              21.196667         25.305000   
550  3/20/2019 10:30:00.000000000 AM              19.453333         24.956667   
598  3/21/2019 10:30:00.000000000 AM              18.160000         24.975000   
646  3/22/2019 10:30:00.000000000 AM              20.400000         24.903333   
694  3/23/2019 10:30:00.000000000 AM              19.036667         25.841667   
742  3/24/2019 10:30:00.000000000 AM              17.588333         26.185000   
790  3/25/2019 10:30:00.000000000 AM              16.670000         23.533333   
838  3/26/2019 10:30:00.000000000 AM              15.810000         26.298333   
886  3/27/2019 10:30:00.000000000 AM              15.286667         22.986667   
934  3/28/2019 10:30:00.000000000 AM              14.236667         26.050000   
982  3/29/2019 10:30:00.000000000 AM              13.590000         26.026667   

     moistureAdd  temperatureAdd  Arrosage  TAfterArrosage  
22      5.731667       -0.018333        10               0  
70      5.533333        0.161667        10               0  
118     8.085000        0.096667        10               0  
166     8.016667        0.035000        10               0  
214     9.481667        3.306667        10               0  
262    12.088333        0.391667        10               0  
310     9.920000        0.143333        10               0  
358    10.123333        0.198333        10               0  
406     9.266667        0.371667        10               0  
454     9.453333        2.196667        10               0  
502     8.291667        0.248333        10               0  
550     5.530000        0.461667        10               0  
598     4.656667        0.323333        10               0  
646     4.796667        0.328333        10               0  
694     3.676667       -0.776667        10               0  
742     5.118333       -1.095000        10               0  
790     6.373333       -1.385000        10               0  
838     6.670000       -0.333333        10               0  
886     6.011667       -0.460000        10               0  
934     8.520000       -1.426667        20               0  
982     7.636667       -0.950000        20               0

In [97]:
regLinearAro = linear_model.LinearRegression()
regLinearAro.fit(dfArrosage[['mean_moisture-percent','mean_temperature','Arrosage']],dfArrosage.moistureAdd)

regLinearAro.intercept_
regLinearAro.coef_

array([ 0.14769565, -0.4213349 ,  0.25450568])

In [76]:
# Pour faire le régression linear sur le moment d'arrosage

regLinearEva = linear_model.LinearRegression()
regLinearEva.fit(dfEvaporation[['mean_moisture-percent','mean_temperature']],dfEvaporation.moistureAdd)

regLinearEva.intercept_
regLinearEva.coef_

array([-0.02033151, -0.02001496])

In [50]:
#Pour tester sur la base de données de training
init = 23+48*5
base = df 

In [77]:
#Pour tester sur la base de données de training
init = 32+48*1
base = dfTest 

In [107]:
StartHumidity = base.iloc[init,1]

TestSize = 40
result = np.zeros(TestSize)
for i in range(0,TestSize):
    result[i] = StartHumidity + regLinearEva.predict([[StartHumidity,base.iloc[init+i,2]]])[0]
    StartHumidity = result[i]

#print(result)
#print(base.iloc[range(0+init-1,TestSize+init+1),1])
ErrAro = base.iloc[init,1] - (base.iloc[init-1,1] +
      regLinearAro.predict([[base.iloc[init-1,1],base.iloc[init-1,2],base.iloc[init-1,5]]])[0])
ErrEva = np.mean(base.iloc[range(0+init+1,TestSize+init+1),1].values-result)

#print(base.iloc[init,1])
#print(base.iloc[init-1,1] +
#      regLinearAro.predict([[base.iloc[init-1,1],base.iloc[init-1,2],base.iloc[init-1,5]]])[0])
print("Erreur d'Arrosage : ", ErrAro)
print("Moyenne d'erreur evaporation : ", ErrEva)

Erreur d'Arrosage :  0.987879073952
Moyenne d'erreur evaporation :  -4.68581804485


# Affichage des résultats

On Affiche les resultats

In [105]:
print("Sans le temps : ", ErrSansTemps)
print("Avec le temps : ", ErrTemps)
print("Durant Arrosage : ",ErrAro)
print("Evaporation : " , ErrEva)
print("Rassemblé : ", ErrAro + ErrEva)


Sans le temps :  -4.64522098199
Avec le temps :  -2.21106280251
Durant Arrosage :  0.987879073952
Evaporation :  -4.68581804485
Rassemblé :  -3.6979389709
