# First implementation of Machine Learning Algorithm

In this file, we are going to import data from a file .csv that we take from chornograf.
We have to parse him and put into an array.
Finally we will insert some machin Learning algorithm with the librairy sklearn.

To do this, we will use some librairy as pandas, matplotlib, numpy, sklearn and some others.


Le fichier data2learn2.csv a pour query ceci : 

SELECT mean("moisture-percent") AS "mean_moisture-percent" ,  mean("temperature") AS "mean_temperature"

FROM "demeter"."autogen"."chirp-left" 

WHERE time > now() - 1200h AND time < now() -700h

GROUP BY time(30m)

In [1]:
import csv
import math
import matplotlib.pyplot as plt
import numpy as np

#Data place 
tabl = []

name = 'Data2learn.csv'
nameTabl = []
with open(name) as csv_file:
    csv_reader = csv.reader(csv_file, delimiter=',')
    ligne = 0
    for row in csv_reader:
        if ligne != 0:
            i = 0
            for el in row:
                tabl[i].append(el)
                i += 1
        else:
            for el in row:
                tabl.append([])
                nameTabl.append(el)
                
        ligne += 1
        
#print(tabl)
print(nameTabl)



['date', 'mean_moisture-percent', 'mean_temperature']


# Import des données 

Leccture d'un fichier csv en un fichier dataframe.

Création d'une base dataframe avec comme colonne le temps, l'humidité, la tempérture, l'humidité + 1, la température + 1.

Il faut régler le problème tu dernier temps.

In [1]:
import csv
import math
import pandas as pd
import numpy as np

df = pd.read_csv('Data2learn2.csv')
#print(df)
#print(df.iloc[:,2])

#Création des deux autres colonnes
df['moistureAdd'] = df.index
df['temperatureAdd'] = df.index

# size
nligne = df.shape[0]
nColumn = df.shape[1]
tmp = np.linspace(0,nligne-2,nligne-1,dtype=int)
df.iloc[tmp, 3] = pd.Series(np.append(df.iloc[tmp+1,1].to_numpy()-df.iloc[tmp,1].to_numpy(),0), index=df.index)
df.iloc[tmp, 4] = pd.Series(np.append(df.iloc[tmp+1,2].to_numpy()-df.iloc[tmp,2].to_numpy(),0), index=df.index)

#Ajout de la ligne
df.iloc[nligne-1, 3] = 0
df.iloc[nligne-1, 4] = 0


#df


# Ajout de l'arrosage

L'arrosage est ajouté au temps 10h30.

In [2]:
df['Arrosage'] = df.index
liste10h30 = np.linspace(22,982,int((982-22)/48)+1)

df.iloc[:,5] = 0
for i in liste10h30:
    if i >= 934:
        df.iloc[int(i),5] = 20
    else:
        df.iloc[int(i),5] = 10



Ajout du temps après chaque arrosage

In [3]:
df['TAfterArrosage'] = df.index

df.iloc[:,6] = 0
for i in np.append(-26,liste10h30):
    for j in range(0,48):
        if i+j < nligne:
            df.iloc[int(i+j),6] = j*30

df


date  mean_moisture-percent  \
0      3/8/2019 11:30:00.000000000 PM              31.436364   
1      3/9/2019 12:00:00.000000000 AM              31.360000   
2      3/9/2019 12:30:00.000000000 AM              31.363333   
3       3/9/2019 1:00:00.000000000 AM              31.353333   
4       3/9/2019 1:30:00.000000000 AM              31.303333   
5       3/9/2019 2:00:00.000000000 AM              31.360000   
6       3/9/2019 2:30:00.000000000 AM              31.416667   
7       3/9/2019 3:00:00.000000000 AM              31.406667   
8       3/9/2019 3:30:00.000000000 AM              31.363333   
9       3/9/2019 4:00:00.000000000 AM              31.366667   
10      3/9/2019 4:30:00.000000000 AM              31.323333   
11      3/9/2019 5:00:00.000000000 AM              31.296667   
12      3/9/2019 5:30:00.000000000 AM              31.276667   
13      3/9/2019 6:00:00.000000000 AM              31.343333   
14      3/9/2019 6:30:00.000000000 AM              31.333333   
15      3/9/2019 7:00:00.000000000 AM              31.410000   
16      3/9/2019 7:30:00.000000000 AM              31.366667   
17      3/9/2019 8:00:00.000000000 AM              31.430000   
18      3/9/2019 8:30:00.000000000 AM              31.383333   
19      3/9/2019 9:00:00.000000000 AM              31.356667   
20      3/9/2019 9:30:00.000000000 AM              31.366667   
21     3/9/2019 10:00:00.000000000 AM              31.410000   
22     3/9/2019 10:30:00.000000000 AM              31.540000   
23     3/9/2019 11:00:00.000000000 AM              37.271667   
24     3/9/2019 11:30:00.000000000 AM              35.583333   
25     3/9/2019 12:00:00.000000000 PM              35.160000   
26     3/9/2019 12:30:00.000000000 PM              34.813333   
27      3/9/2019 1:00:00.000000000 PM              34.440000   
28      3/9/2019 1:30:00.000000000 PM              34.340000   
29      3/9/2019 2:00:00.000000000 PM              33.943333   
...                               ...                    ...   
971    3/29/2019 5:00:00.000000000 AM              13.910000   
972    3/29/2019 5:30:00.000000000 AM              13.816667   
973    3/29/2019 6:00:00.000000000 AM              13.806667   
974    3/29/2019 6:30:00.000000000 AM              13.833333   
975    3/29/2019 7:00:00.000000000 AM              13.750000   
976    3/29/2019 7:30:00.000000000 AM              13.813333   
977    3/29/2019 8:00:00.000000000 AM              13.840000   
978    3/29/2019 8:30:00.000000000 AM              13.846667   
979    3/29/2019 9:00:00.000000000 AM              14.283333   
980    3/29/2019 9:30:00.000000000 AM              14.016667   
981   3/29/2019 10:00:00.000000000 AM              13.720000   
982   3/29/2019 10:30:00.000000000 AM              13.590000   
983   3/29/2019 11:00:00.000000000 AM              21.226667   
984   3/29/2019 11:30:00.000000000 AM              17.355000   
985   3/29/2019 12:00:00.000000000 PM              16.646667   
986   3/29/2019 12:30:00.000000000 PM              15.893333   
987    3/29/2019 1:00:00.000000000 PM              15.263333   
988    3/29/2019 1:30:00.000000000 PM              14.686667   
989    3/29/2019 2:00:00.000000000 PM              14.133333   
990    3/29/2019 2:30:00.000000000 PM              13.733333   
991    3/29/2019 3:00:00.000000000 PM              13.166667   
992    3/29/2019 3:30:00.000000000 PM              12.820000   
993    3/29/2019 4:00:00.000000000 PM              12.780000   
994    3/29/2019 4:30:00.000000000 PM              13.553333   
995    3/29/2019 5:00:00.000000000 PM              13.886667   
996    3/29/2019 5:30:00.000000000 PM              13.973333   
997    3/29/2019 6:00:00.000000000 PM              13.953333   
998    3/29/2019 6:30:00.000000000 PM              13.870000   
999    3/29/2019 7:00:00.000000000 PM              13.776667   
1000   3/29/2019 7:30:00.000000000 PM              13.900000   

      mean_temperature  moistureAdd  temperatureAdd  Arrosage  T

# Analyse de la dataFrame


# Linear Regression Multiple Variables sans l'information sur le temps sans arrosage



In [4]:
from sklearn import linear_model

reg = linear_model.LinearRegression()
reg.fit(df[['mean_moisture-percent','mean_temperature','Arrosage']],df.moistureAdd)



LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [5]:
reg.coef_

array([-0.01619655, -0.02062898,  0.64269237])

In [6]:
reg.intercept_

0.75662954892605394

In [7]:
reg.predict([[31,25,10]])[0]

6.1657357937024271

# Linear Regression Multiple Variables AVEC l'information sur le temps sans arrosage

In [33]:
reg2 = linear_model.LinearRegression()
reg2.fit(df[['mean_moisture-percent','mean_temperature','Arrosage','TAfterArrosage']],df.moistureAdd)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [34]:
reg2.coef_

array([ -5.70216010e-03,   1.31717487e-02,   6.78979076e-01,
         4.91427599e-04])

In [35]:
reg2.intercept_

-0.73980634783026533

In [36]:
reg2.predict([[31,25,10,0]])[0]

6.2025111667703925

# Test de mes résultats

SANS DES DONNÉES POUR VERIFICATIONS. PAS DE DATA TEST.

Le but est de faire une boucle sur une période en utilisant les valeurs obtenus à l'itérations précédentes

Creation de liste de planification de l'arrosage pour le test

In [12]:
TestSize = 20 #Taille du Test

testArrosage = np.zeros(TestSize)
testArrosage[2] = 10  #Position de notre arrosage et valeur
testArrosage

array([  0.,   0.,  10.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.])

Création de la liste de plannification de la temperature pour notre test

In [13]:
PosTemperature = np.linspace(980,980+TestSize-1,TestSize)
testTemperature = (df.iloc[PosTemperature, 2]).values
testTemperature

array([ 23.80166667,  25.42333333,  26.02666667,  25.07666667,
        26.195     ,  27.54833333,  30.95      ,  34.26      ,
        34.71      ,  36.22      ,  37.        ,  39.77166667,
        41.91333333,  40.08666667,  30.915     ,  28.08      ,
        27.91333333,  27.76166667,  27.52166667,  27.095     ])

Mise en place du test sur le nombre d'itération souhaité

In [14]:
StartHumidity = 10
result = np.zeros(TestSize)
for i in range(0,TestSize):
    result[i] = StartHumidity + reg.predict([[StartHumidity,testTemperature[i],testArrosage[i]]])[0]
    StartHumidity = result[i]

result

array([ 10.10365999,  10.17218771,  16.65408308,  16.62366794,
        16.57067535,  16.49062317,  16.34169465,  16.12689634,
        15.90629397,  15.65811485,  15.39786476,  15.08465318,
        14.73233414,  14.42340373,  14.30867904,  14.25429565,
        14.20423125,  14.15810645,  14.11767966,  14.08670935])

# Test avec data Test

Création d'une data frame pour effectuer les tests.

Voici la query effectuer pour obtenir les données.

SELECT mean("moisture-percent") AS "mean_moisture-percent" ,  mean("temperature") AS "mean_temperature"

FROM "demeter"."autogen"."chirp-left" 

WHERE time > now() - 700h AND time < now() -400h

GROUP BY time(30m)

In [15]:
dfTest = pd.read_csv('DataTest.csv')

dfTest['moistureAdd'] = dfTest.index
dfTest['temperatureAdd'] = dfTest.index


# size
nligneTest = dfTest.shape[0]
nColumnTest = dfTest.shape[1]
tmp = np.linspace(0,nligneTest-2,nligneTest-1,dtype=int)
dfTest.iloc[tmp, 3] = pd.Series(np.append(dfTest.iloc[tmp+1,1].to_numpy()-dfTest.iloc[tmp,1].to_numpy(),0), index=dfTest.index)
dfTest.iloc[tmp, 4] = pd.Series(np.append(dfTest.iloc[tmp+1,2].to_numpy()-dfTest.iloc[tmp,2].to_numpy(),0), index=dfTest.index)

#Ajout de la ligne
dfTest.iloc[nligneTest-1, 3] = 0


In [16]:
dfTest['Arrosage'] = dfTest.index
liste11h30 = np.linspace(31,559,int((559-31)/48)+1)

dfTest.iloc[:,5] = 0
for i in liste11h30:
    dfTest.iloc[int(i),5] = 20



In [17]:
dfTest['TAfterArrosage'] = dfTest.index

dfTest.iloc[:,6] = 0
for i in np.append(-17,liste11h30):
    for j in range(0,48):
        if i+j < nligneTest:
            dfTest.iloc[int(i+j),6] = j*30

dfTest

date  mean_moisture-percent  mean_temperature  \
0     3/30/2019 7:00:00.000000000 PM              13.583721         27.283721   
1     3/30/2019 7:30:00.000000000 PM              13.493333         27.473333   
2     3/30/2019 8:00:00.000000000 PM              13.513333         27.356667   
3     3/30/2019 8:30:00.000000000 PM              13.496667         27.180000   
4     3/30/2019 9:00:00.000000000 PM              13.503333         27.015000   
5     3/30/2019 9:30:00.000000000 PM              13.476667         26.841667   
6    3/30/2019 10:00:00.000000000 PM              13.486667         26.730000   
7    3/30/2019 10:30:00.000000000 PM              13.423333         26.700000   
8    3/30/2019 11:00:00.000000000 PM              13.436667         26.691667   
9    3/30/2019 11:30:00.000000000 PM              13.456667         26.603333   
10   3/31/2019 12:00:00.000000000 AM              13.380000         26.595000   
11   3/31/2019 12:30:00.000000000 AM              13.443333         26.585000   
12    3/31/2019 1:00:00.000000000 AM              13.430000         26.511667   
13    3/31/2019 1:30:00.000000000 AM              13.403333         26.461667   
14    3/31/2019 3:00:00.000000000 AM              13.423333         26.400000   
15    3/31/2019 3:30:00.000000000 AM              13.413333         26.400000   
16    3/31/2019 4:00:00.000000000 AM              13.393333         26.386667   
17    3/31/2019 4:30:00.000000000 AM              13.400000         26.305000   
18    3/31/2019 5:00:00.000000000 AM              13.340000         26.300000   
19    3/31/2019 5:30:00.000000000 AM              13.393333         26.276667   
20    3/31/2019 6:00:00.000000000 AM              13.320000         25.993333   
21    3/31/2019 6:30:00.000000000 AM              13.260000         25.893333   
22    3/31/2019 7:00:00.000000000 AM              13.420000         25.833333   
23    3/31/2019 7:30:00.000000000 AM              13.320000         25.800000   
24    3/31/2019 8:00:00.000000000 AM              13.353333         25.800000   
25    3/31/2019 8:30:00.000000000 AM              13.366667         25.800000   
26    3/31/2019 9:00:00.000000000 AM              13.386667         25.800000   
27    3/31/2019 9:30:00.000000000 AM              13.310000         25.800000   
28   3/31/2019 10:00:00.000000000 AM              13.380000         26.165000   
29   3/31/2019 10:30:00.000000000 AM              13.376667         26.005000   
..                               ...                    ...               ...   
571   4/11/2019 5:30:00.000000000 PM              16.246667         26.290000   
572   4/11/2019 6:00:00.000000000 PM              16.520000         24.273333   
573   4/11/2019 6:30:00.000000000 PM              16.383333         25.478333   
574   4/11/2019 7:00:00.000000000 PM              16.280000         25.956667   
575   4/11/2019 7:30:00.000000000 PM              16.216667         26.136667   
576   4/11/2019 8:00:00.000000000 PM              16.040000         25.875000   
577   4/11/2019 8:30:00.000000000 PM              16.020000         25.780000   
578   4/11/2019 9:00:00.000000000 PM              15.930000         25.700000   
579   4/11/2019 9:30:00.000000000 PM              15.986667         25.623333   
580  4/11/2019 10:00:00.000000000 PM              15.966667         25.578333   
581  4/11/2019 10:30:00.000000000 PM              15.910000         25.500000   
582  4/11/2019 11:00:00.000000000 PM              15.936667         25.500000   
583  4/11/2019 11:30:00.000000000 PM              15.893333         25.500000   
584  4/12/2019 12:00:00.000000000 AM              15.870000         25.501667   
585  4/12/2019 12:30:00.000000000 AM              15.786667         25.500000   
586   4/12/2019 1:00:00.000000000 AM              15.896667         25.500000   
587   4/12/2019 1:30:00.000000000 AM              15.870000         25.500000   
588   4/12/2019 2:00:00.000000000 AM              15.793333    

TEST AVEC LES DONNEES SANS LE TEMPS

In [41]:
init = 28+48
StartHumidity = dfTest.iloc[init,1]

TestSize = 50
result = np.zeros(TestSize)
for i in range(0,TestSize):
    result[i] = StartHumidity + reg.predict([[StartHumidity,dfTest.iloc[init+i,2],dfTest.iloc[init+i,5]]])[0]
    StartHumidity = result[i]

#print(result)

#print(dfTest.iloc[range(0+init+1,TestSize+init+1),1])

print(np.sum(dfTest.iloc[range(0+init+1,TestSize+init+1),1].values-result)/TestSize)

0.647176886303


TEST AVEC LES DONNES AVEC LE TEMPS

In [40]:
init = 28+48
StartHumidity = dfTest.iloc[init,1]

TestSize = 50
result2 = np.zeros(TestSize)
for i in range(0,TestSize):
    result2[i] = StartHumidity + reg2.predict([[StartHumidity,dfTest.iloc[init+i,2],dfTest.iloc[init+i,5],dfTest.iloc[init+i,6]]])[0]
    StartHumidity = result2[i]

#print(result2)

#print(dfTest.iloc[range(0+init+1,TestSize+init+1),1])

print(np.sum(dfTest.iloc[range(0+init+1,TestSize+init+1),1].values-result2)/TestSize)

-6.28040363105
